### ISSUE TITLE
i cant compile with c++

### ISSUE THREAD

**Issue by ghost** [MrAntrophy/MinecraftUnrealEngine#2]
it say,missing plugin and rebuilt with difrent version,can u say what unreal verison to make this project?

**Comment by Antrophyy** [comment]
Hello,

I fixed it but it seems the game was broken either way. 

I tried to see what broke it and it seems that the upgrade to UE5 broke chunk spawning completely. 

So I reverted to the last working commit, which is using UE 4.27.

I may update the project to 5.2.1 and fix the chunk spawning later but I don't know when that is going to be.

**Comment by ghost** [comment]
i installed ue4 and when compiling it c++, the error still appears, is it possible to upgrade to ue5 or do you have a way

**Comment by Antrophyy** [comment]
@kimjongchien I updated the project to be compilable without PCH and it runs just fine for me.

I downloaded 4.27.2 UE version on Epic launcher, double clicked the checked out latest and while it did say "Game is compiled using different engine version" I clicked "Rebuild" and after a little while it opened up.

PS: Make sure to select 4.27.2 here in the Epic Launcher before double clicking the project, otherwise it will try to launch it in whatever version you have selected here 
![image](https://github.com/Antrophyy/MinecraftUnrealEngine/assets/34379991/810d4a45-870b-4817-ac49-87727a3b691a)

if you are running it from an IDE, it should work just fine without you having to do anything extra.
